- Agent/src/main/java/net/hawkengine/agent/AgentConfiguration.java
- Agent/src/main/java/net/hawkengine/agent/components/taskexecutor/executors/ExecTaskExecutor.java
- Agent/src/test/java/net/hawkengine/agent/components/taskexecutor/executors/ExecTaskExecutorTest.java
- Agent/src/test/java/net/hawkengine/agent/components/taskexecutor/executors/ExecTaskExecutorTestOnLinux.java
- Agent/src/test/java/net/hawkengine/agent/components/taskexecutor/executors/ExecTaskExecutorTestOnWindows.java
- Agent/src/test/java/net/hawkengine/agent/components/taskexecutor/executors/FetchArtifactExecutorTest.java
- Agent/src/test/java/net/hawkengine/agent/components/taskexecutor/executors/FetchMaterialExecutorTest.java
- Agent/src/test/java/net/hawkengine/agent/components/taskexecutor/executors/RunOnlyOnLinux.java
- Agent/src/test/java/net/hawkengine/agent/components/taskexecutor/executors/RunOnlyOnWindows.java
- Agent/src/test/java/net/hawkengine/agent/components/taskexecutor/executors/UploadArtifactExecutorTest.java
- Server/src/main/java/net/hawkengine/http/AgentController.java
- Server/src/main/java/net/hawkengine/model/Job.java
- Server/src/main/java/net/hawkengine/services/AgentService.java
> Exec executor refactoring

- Server/src/main/java/net/hawkengine/services/TaskDefinitionService.java
- Server/src/test/java/net/hawkengine/services/tests/TaskDefinitionServiceTests.java
- Server/ui/src/app/pipelines/controllers/pipelineConfig.controller.js
- Server/ui/src/app/pipelines/views/partials/config/job-options/_add-task.html
- Server/ui/src/app/pipelines/views/partials/config/job-options/_edit-task.html
> UI styling and functionality implementation.

- Agent/src/main/java/net/hawkengine/agent/AgentConfiguration.java
- Server/src/main/java/net/hawkengine/services/AgentService.java
- Server/ui/src/app/application/services/viewModel/viewModelUpdater.service.js
- Server/ui/src/app/application/services/ws/websocketReceiver.service.js
> UI update after Agent registering in app.

- Server/ui/src/app/pipelines/controllers/pipelineConfig.controller.js
> Fixed tasks not being editable

- Server/ui/src/app/pipelines/views/partials/config/job-options/_add-task.html
> Materials are showed when fetch material task is added.

- Agent/src/main/java/net/hawkengine/agent/components/taskexecutor/executors/ExecTaskExecutor.java
- Agent/src/main/java/net/hawkengine/agent/models/ExecTask.java
- Agent/src/test/java/net/hawkengine/agent/components/taskexecutor/executors/ExecTaskExecutorTestOnLinux.java
- Agent/src/test/java/net/hawkengine/agent/components/taskexecutor/executors/ExecTaskExecutorTestOnWindows.java
- Server/src/main/java/net/hawkengine/core/utilities/SchemaValidator.java
- Server/src/main/java/net/hawkengine/model/ExecTask.java
- Server/src/test/java/net/hawkengine/core/utilities/SchemaValidatorTests.java
- Server/src/test/java/net/hawkengine/services/tests/TaskDefinitionServiceTests.java
- Server/ui/src/app/pipelines/controllers/pipelineConfig.controller.js
- Server/ui/src/app/pipelines/controllers/pipelines.controller.js
> Refactored logic for ExecTaskExecutor for initial input arguments.

- Agent/src/main/java/net/hawkengine/agent/components/taskexecutor/executors/ExecTaskExecutor.java
- Server/ui/src/app/pipelines/controllers/pipelineConfig.controller.js
- Server/ui/src/app/pipelines/views/partials/config/job-options/_tasks.html
Implemented drag and drop functionality for tasks on the UI #96
> Fixed tasks not being sortable

- Server/src/main/java/net/hawkengine/services/PipelineDefinitionService.java
- Server/src/main/java/net/hawkengine/services/UserService.java
- Server/src/main/java/net/hawkengine/services/filters/SecurityService.java
- Server/src/main/java/net/hawkengine/services/filters/factories/SecurityServiceInvoker.java
- Server/src/main/java/net/hawkengine/services/filters/interfaces/ISecurityService.java
- Server/src/main/java/net/hawkengine/services/interfaces/IUserService.java
- Server/src/main/java/net/hawkengine/ws/WsEndpoint.java
- Server/src/test/java/net/hawkengine/services/tests/PipelineDefinitionServiceTests.java
- Server/src/test/java/net/hawkengine/services/tests/filters/SecurityServiceTests.java
- Server/ui/src/app/admin/services/users.service.js
- Server/ui/src/app/application/services/ws/websocketReceiver.service.js
- Server/ui/src/app/profile/controllers/user.controller.js
- Server/ui/src/app/profile/views/index.html
- Server/ui/src/app/profile/views/partials/_change-password.html
- Server/ui/src/app/profile/views/partials/_changePassword.html
> Implemented change user password 

- Server/ui/src/app/admin/views/partials/_assignUsers.html
> Updated Assign Users button look

- Server/ui/src/app/admin/controllers/admin.controller.js
- Server/ui/src/app/admin/views/partials/_groups.html
- Server/ui/src/app/admin/views/partials/_userGroups.html
- Server/ui/src/app/styles/custom.css
Fixed buttons incorrectly expanding accordions on User Group and Pipeline Group views #135 #130
> Changed logic for accordion expansion 

- Server/ui/src/app/admin/views/partials/_add-material.html
- Server/ui/src/app/admin/views/partials/_add-user.html
- Server/ui/src/app/admin/views/partials/_add-userGroup.html
- Server/ui/src/app/admin/views/partials/_edit-material.html
- Server/ui/src/app/admin/views/partials/_manageUserGroup.html
Added validation for adding Materials, adding Users, adding User Groups, editing Materials and editing User Groups #134 #132
> Fixed Bug-134 and Bug-132

- Server/src/main/java/net/hawkengine/core/pipelinescheduler/StatusUpdaterService.java
- Server/ui/src/app/pipelines/views/partials/pipeline-history/_medium-devices.html
- Server/ui/src/app/pipelines/views/partials/pipeline-history/_small-devices.html
- Server/ui/src/app/pipelines/views/partials/pipeline-management/_pipeline.html
- Server/ui/src/app/pipelines/views/partials/run-management/_materials.html
- Server/ui/src/app/pipelines/views/partials/run-management/_stage.html
- Server/ui/src/app/styles/custom.css
- Server/ui/src/app/styles/history-screen/_medium-devices.css
Implemented the ability to cancel Pipelines on the Server and UI #185
> Cancel pipeline implementation

- Server/src/main/java/net/hawkengine/core/HawkServer.java
- Server/src/main/java/net/hawkengine/core/utilities/DataImporter.java
- Server/src/main/java/net/hawkengine/services/PipelineGroupService.java
- Server/src/main/java/net/hawkengine/services/UserService.java
- Server/src/main/java/net/hawkengine/services/interfaces/IUserService.java
- Server/src/test/java/net/hawkengine/core/utilities/DataImporterTests.java
- Server/src/test/java/net/hawkengine/services/tests/filters/PipelineGroupAuthorizationServiceTests.java
- Server/src/test/java/net/hawkengine/services/tests/filters/SecurityServiceTests.java
- Server/ui/src/app/pipelines/controllers/pipelines.controller.js
> Fixed Pipeline permission when there is no Pipeline Group permission

- Server/src/main/java/net/hawkengine/http/AgentController.java
- Server/src/main/java/net/hawkengine/ws/WsEndpoint.java
- Server/ui/src/app/pipelines/controllers/pipelinesRunManagement.controller.js
- Server/ui/src/app/pipelines/views/partials/run-management/_materials.html
Fixed missing property binding in AgentController when agent is reporting itself #181
> Added missing Agent status reporting property #181

- Server/ui/src/app/application/services/login.service.js
- Server/ui/src/app/application/services/utility/common-utilities.js
- Server/ui/src/app/application/services/utility/moment.js
- Server/ui/src/app/pipelines/controllers/pipelineConfig.controller.js
- Server/ui/src/app/pipelines/controllers/pipelines.controller.js
- Server/ui/src/app/pipelines/controllers/pipelinesHistory.controller.js
- Server/ui/src/app/pipelines/controllers/pipelinesRunManagement.controller.js
- Server/ui/src/app/pipelines/views/partials/config/pipeline-options/_stages.html
Added ability to reorder stages #193
> Feature 193

- Server/ui/src/app/pipelines/controllers/pipelineConfig.controller.js
- Server/ui/src/app/pipelines/hawk.pipelinesManagement.js
- Server/ui/src/app/pipelines/views/partials/config/_job-config.html
- Server/ui/src/app/pipelines/views/partials/config/job-options/_add-resource.html
- Server/ui/src/app/pipelines/views/partials/config/job-options/_edit-resource.html
- Server/ui/src/app/pipelines/views/partials/config/job-options/_remove-resource.html
- Server/ui/src/app/pipelines/views/partials/config/job-options/_resources.html
Added ability to Add, Edit and Delete Resources for Jobs #222
> Feature 222

- Server/src/main/java/net/hawkengine/services/JobDefinitionService.java
- Server/src/main/java/net/hawkengine/services/StageDefinitionService.java
> Fixed add job and stage with default task definitions

- Server/ui/src/app/application/controllers/app.controller.js
- Server/ui/src/app/application/views/layout/header.html
Implemented displaying of the currently logged user in the header #230
> Feature 230

- Agent/agent.sh
- build1.sh
partial implementation of the upgrade strategy
> Feature 286

- Server/src/main/java/net/hawkengine/core/pipelinescheduler/StatusUpdaterService.java
- Server/src/main/java/net/hawkengine/model/enums/StageStatus.java
- Server/src/main/java/net/hawkengine/model/enums/Status.java
- Server/ui/src/app/pipelines/controllers/pipelines.controller.js
- Server/ui/src/app/pipelines/controllers/pipelinesRunManagement.controller.js
- Server/ui/src/app/pipelines/services/pipelineExec.service.js
- Server/ui/src/app/pipelines/views/partials/pipeline-management/_pipeline.html
- Server/ui/src/app/pipelines/views/partials/run-management/_runs-info.html
- Server/ui/src/app/pipelines/views/partials/run-management/_stage.html
- build1.sh
Implemented Continue Stage functionality #287
> Feature 287

- Server/ui/src/app/pipelines/views/partials/run-management/_materials.html
Fixed Materials label in Run Management screen #248
> Enhancement 248

- Server/ui/src/app/application/common/directives.js
- Server/ui/src/app/pipelines/controllers/pipelineConfig.controller.js
- Server/ui/src/app/pipelines/views/partials/config/_job-config-medium.html
- Server/ui/src/app/pipelines/views/partials/config/_job-config-small.html
- Server/ui/src/app/pipelines/views/partials/config/_job-config.html
- Server/ui/src/app/pipelines/views/partials/config/_pipeline-config-medium.html
- Server/ui/src/app/pipelines/views/partials/config/_pipeline-config-small.html
- Server/ui/src/app/pipelines/views/partials/config/_pipeline-config.html
- Server/ui/src/app/pipelines/views/partials/config/_stage-config-medium.html
- Server/ui/src/app/pipelines/views/partials/config/_stage-config-small.html
- Server/ui/src/app/pipelines/views/partials/config/_stage-config.html
- Server/ui/src/app/pipelines/views/partials/config/job-options/_resources.html
- Server/ui/src/app/pipelines/views/partials/config/job-options/_settings.html
- Server/ui/src/app/pipelines/views/partials/config/job-options/_tasks.html
- Server/ui/src/app/pipelines/views/partials/config/job-options/_variables.html
- Server/ui/src/app/pipelines/views/partials/config/pipeline-options/_general-options.html
- Server/ui/src/app/pipelines/views/partials/config/pipeline-options/_stages.html
- Server/ui/src/app/pipelines/views/partials/config/pipeline-options/_variables.html
- Server/ui/src/app/pipelines/views/partials/config/stage-options/_jobs.html
- Server/ui/src/app/pipelines/views/partials/config/stage-options/_settings.html
- Server/ui/src/app/pipelines/views/partials/config/stage-options/_variables.html
- Server/ui/src/app/pipelines/views/partials/pipeline-management/_pipeline.html
- Server/ui/src/app/styles/custom.css
Added responsiveness for Pipeline, Stage and Job Config screens #263 #264 #266 #267 #268 #269 #270 #271 #272 #265
> Config screen responsive design

- Server/ui/src/app/admin/controllers/admin.controller.js
- Server/ui/src/app/admin/views/index-medium.html
- Server/ui/src/app/admin/views/index-small.html
- Server/ui/src/app/admin/views/index.html
- Server/ui/src/app/admin/views/partials/_groups.html
- Server/ui/src/app/admin/views/partials/_manageUser.html
- Server/ui/src/app/admin/views/partials/_materials.html
- Server/ui/src/app/admin/views/partials/_userActions-small.html
- Server/ui/src/app/admin/views/partials/_userGroups.html
- Server/ui/src/app/admin/views/partials/_users.html
- Server/ui/src/app/pipelines/views/partials/config/_job-config-medium.html
- Server/ui/src/app/pipelines/views/partials/config/_job-config-small.html
- Server/ui/src/app/pipelines/views/partials/config/_pipeline-config-medium.html
- Server/ui/src/app/pipelines/views/partials/config/_pipeline-config-small.html
- Server/ui/src/app/pipelines/views/partials/config/_stage-config-medium.html
- Server/ui/src/app/pipelines/views/partials/config/_stage-config-small.html
- Server/ui/src/app/styles/custom.css
Added responsiveness for Admin screen #278 #279 #280 #281 #430
> Admin screen responsive 

- Server/ui/src/app/artifacts/views/index.html
- Server/ui/src/app/styles/artifacts-screen/_medium-devices.css
- Server/ui/src/app/styles/custom.css
Added responsiveness for Admin screen #431
> Artifacts screen responsive design
